spring:
  application:
    name: spring-cloud-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8765

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/